import 'package:flumoxs/screens/home/widgets/product.dart';

final List<product> products = [
  const product(kategori: 'Make Up',/*category: 'Make Up',*/id: '0',image: "assets/images/Kel.2(art painting).jpg",description: 'Make up karekter adalah suatu tata rias atau make up yang terapkan untuk mengubah penampilan seseorang dalam berbagai hal. Hal yang dimaksud adalah mengenai umur, sifat, wajah, suku, dan bangsa.',name: 'Make Up Character'),
  const product(kategori: 'Product',/*category: 'Product',*/id: '1',image: "assets/images/Kel.3(Gamora Production).jpg",description: 'Kegiatan mengiklankan produk atau merek yang menghasilkan suatu penjualan dan menciptakan loyalitas atas merek tersebut.',name: 'Product Promotion'),
  const product(kategori: 'Foto Custom',/*category: 'Foto Custom',*/id: '2',image: "assets/images/Kel.4(Agen Fashion Photo).jpg", description: 'Fashion photography adalah sebuah karya seni yang dibantu oleh cahaya lensa kamera yang dikhususkan untuk memotret model dengan dibantu pencahayaan yang glamour, selain difokuskan pada model, fashion photography juga memotret sebuah item fashion seperti baju, tas, sepatu, aksesoris dan make up.',name: 'Fashion Photo'),
  const product(kategori: 'Desain Baju',/*category: 'Desain Baju',*/id: '3',image: "assets/images/Kel.5(Street Society).jpg", description: 'Desain baju adalah proses yang sangat rinci mulai dari memilih desain dan berakhir dengan pengembangan produk akhir yang sempurna. Cara desain baju terdiri dari pemilihan elemen yang melibatkan seni menerapkan desain, estetika dan keindahan alam kepada pakaian dan aksesorinya.',name: 'Desain Baju'),
  const product(kategori: 'Poster',/*category: 'Poster Custom',*/id: '4',image: "assets/images/Kel.6(Develop Production).jpg", description: ' Poster adalah suatu media publikasi yang memadukan antara tulisan, gambar, atau kombinasi keduanya dengan tujuan untuk memberikan informasi kepada khalayak.',name: 'Poster'),
  const product(kategori: 'Foto',/*category: 'Foto & Video',*/id: '5',image: "assets/images/Kel.7(Memory Apik).jpg", description: 'Foto moment adalah istilah yang digunakan untuk menggambarkan foto yang diambil pada saat-saat penting atau bersejarah. Foto moment dapat berupa foto pernikahan, foto keluarga, foto liburan, atau foto lainnya yang memiliki arti emosional bagi orang yang mengambil atau melihatnya.',name: 'Foto Moment'),
  const product(kategori: 'Food',/*category: 'Food',*/ id: '6',image: "assets/images/Kel.8(Techara).jpg", description: 'Promotion adalah suatu kegiatan yang dilakukan agar bisa meningkatkan perkembangan sesuatu, baik itu merek, produk, ataupun perusahaan itu sendiri',name: 'Food Promotion'),
  //const product(image: "assets/thumbnail/video-capture-7273.png", description: "", name: "", id: "7", kategori: "")
];